### PR TITLE
Fixes and updates

### PR DESCRIPTION
**Pull request by railsmechanic**
- Fixed the issue of the inconsistent length of strings generated with the hex function
- Updated generation of base64 encoded data

### CODE REVIEW

**Comment by patricksrobertson** [comment]
@railsmechanic do you mind removing the updates to mix? I'd prefer to manage release separately.

**Comment by patricksrobertson** [comment]
Thanks for the PR!

**Comment by patricksrobertson** [comment]
@railsmechanic I pulled this in red, I needed to do a slight overhaul to the TravisCI build matrix and then update the urlsafe64 encoder as well. As it turns out, this required elixir 1.2 or greater (the encode64 was not introduced until 1.2).

Will do a hex release shortly. Thanks again for the update!

**Comment by railsmechanic** [comment]
@patricksrobertson thanks for the info. 
I'm here to help... :)

**Pull request merged**
